### PR TITLE
robot_state_t decode hack

### PR DESCRIPTION
**Pull request by tkoolen**
On top of #20 and #18.

@rdeits, check out this beautiful hack (last commit), haha.

After this, the only allocations in the controller are from these two lines:

https://github.com/JuliaRobotics/LCMCore.jl/blob/f8e1e0330a8448e6fc9174b8279241cbafe1cc3e/src/core.jl#L139-L140

and this line:

https://github.com/JuliaRobotics/LCMCore.jl/blob/f8e1e0330a8448e6fc9174b8279241cbafe1cc3e/src/core.jl#L186

Any ideas on how to eliminate those?

### CODE REVIEW

**Comment by rdeits** [comment]
Ooooof. Yup, that'll do...

As for those last two allocations, for the channel name we could store the channel strings in the LCM object itself (probably using a trie) and then look up the appropriate stored string using the given bytes (creating and storing it if not present). That would mean that only *new* channel names would allocate. 

For the message bytes themselves, we could just create our own `VeryUnsafeVector <: AbstractVector{UInt8}` and store the data pointer and size in it. We can just implement `size()` and `getindex()` on that type, so it will actually be no less safe than what we're currently doing. We might even be able to use https://github.com/oschulz/UnsafeArrays.jl for this

Actually, we could probably also create an `UnsafeString` using the same idea.

**Comment by rdeits** [comment]
@oschulz this is the potential use case for UnsafeArrays that I was telling you about after the JuliaCon talk today, by the way

**Comment by tkoolen** [comment]
For the public record, there aren't any hacks of this type anywhere below this in the stack. I'd rather not have this hack, but it's just necessary for us right now.

**Comment by oschulz** [comment]
@rdeits, please let me know if you need any additional functionality in UnsafeArrays for this.

**Pull request merged**
