### PR TITLE
Add notebook with QPControl standing controller demo.

### PR DESCRIPTION
**Pull request by tkoolen**
* Rename `LCMController` -> `LCMControlReceiver`
* Add `LCMControlPublisher` (wrapper around a controller that listens for `robot_state_t` and publishes `atlas_command_t`)
* Use `LCMControlPublisher` to set up LCM communication for a `QPControl.StandingController`.
* Reorganize code a bit.

Looks like performance isn't as good as it should be (0.7 x realtime on my machine), but that can be addressed in a separate PR. The robot looks pretty shaky in the visualizer. I wonder if that's because of accuracy issues with encoding/decoding orientations. Also found https://github.com/JuliaRobotics/RigidBodySim.jl/issues/75 in the process of writing this. So not perfect, but a good start.

cc:@rdeits.

### CODE REVIEW

**Comment by tkoolen** [comment]
Now at about 1.2x realtime when running the controller and the simulator in separate Julia processes.

**Comment by rdeits** [comment]
Just tagged a new LCMCore release with the Java and Lua builds turned off: https://github.com/JuliaLang/METADATA.jl/pull/16216

**Comment by tkoolen** [comment]
This probably had something to do with Travis defaulting to xcode 9.4 now.

**Comment by tkoolen** [comment]
https://github.com/MikeInnes/MacroTools.jl/issues/88 now. I'm going to merge this some day, but today is not that day it seems.

**Comment by tkoolen** [comment]
Hallelujah!

**Pull request merged**
